# Generated by Django 4.0.4 on 2022-06-23 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('vehicle_type', models.CharField(choices=[('L', 'Light motor vehicle'), ('H', 'Heavy motor vehicle'), ('T', 'Two wheeled vehicle'), ('O', 'Other')], default='L', max_length=3)),
                ('date', models.DateTimeField(auto_now=True)),
                ('extra_details', models.TextField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_count', models.IntegerField(blank=True, default=1)),
                ('view_count', models.IntegerField(blank=True, default=0)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
