# Generated by Django 4.0.4 on 2022-05-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='shortlist',
            field=models.ManyToManyField(blank=True, null=True, to='app.offer'),
        ),
    ]
