# Generated by Django 4.0.4 on 2022-05-25 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customuser_shortlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image_count',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='offer',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offer',
            name='view_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
