# Generated by Django 4.0.4 on 2022-05-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_offer_image_count_alter_offer_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='view_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
