# Generated by Django 4.0.4 on 2022-05-31 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_notification_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='enquired',
            field=models.ManyToManyField(blank=True, related_name='enquired', to='app.offer'),
        ),
    ]
