# Generated by Django 4.0.4 on 2022-05-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_customuser_shortlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='enquired',
            field=models.ManyToManyField(blank=True, related_name='enquiries', to='app.offer'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='shortlist',
            field=models.ManyToManyField(blank=True, related_name='shortlisted', to='app.offer'),
        ),
    ]
