# Generated by Django 4.0.4 on 2022-06-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_customuser_enquired_alter_customuser_shortlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='vehicle_type',
            field=models.CharField(choices=[('L', 'Light motor vehicle'), ('H', 'Heavy motor vehicle'), ('T', 'Two wheeled vehicle'), ('O', 'Other')], max_length=3, null=True),
        ),
    ]
