# Generated by Django 4.0.4 on 2022-06-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_offer_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='vehicle_type',
            field=models.CharField(choices=[('L', 'Light motor vehicle'), ('H', 'Heavy motor vehicle'), ('T', 'Two wheeled vehicle'), ('O', 'Other')], default='L', max_length=3),
        ),
    ]
